### ISSUE TITLE
自定义预设设为默认后，重启不生效

### ISSUE THREAD

**Issue by milkai** [autodotua/RemoteFFmpegGUI#1]
感谢您提供的工具，WPF版使用中发现自定义预设设为默认后，重后启后不生效。

另外提两个想法：
1. 任务创建后启动队列能否默认设置为不勾选或是记忆上次选择；
2. 输出路径缺省值设置为输入文件所在目录下新建的输出文件夹。

工具很强大！再次感谢:)

**Comment by f-shake** [comment]
感谢你的反馈和建议，提到的BUG已经尝试修复并提交。
关于两个建议，将会在近期更新：
1. 默认设置不勾选这个可以通过设置默认预设来实现。将增加记忆上次选择功能。
2. 将增加默认输出地址的设置选项，并且可以设置“输入文件所在目录下新建的输出文件夹”。

**Comment by f-shake** [comment]
已更新并发布，可以尝试使用。因为技术限制，以及最近时间有限，可能有些问题。

**Comment by milkai** [comment]
:+1::+1::+1:
