### ISSUE TITLE
大佬是否考虑集成将序列帧转为视频的功能

### ISSUE THREAD

**Issue by bjw321** [autodotua/RemoteFFmpegGUI#2]

**Comment by f-shake** [comment]
确实是个有必要的功能，之后有空了会加上

**Comment by bjw321** [comment]
感谢

**Comment by f-shake** [comment]
你好，帧转视频大致的功能已经完成，方法是：在桌面端，在新增转码任务界面，点击时间输入框右侧的“...”，勾选图像序列，输入目标帧率，然后选择图像序列的首个文件；在Web端类似。图像序列的格式满足[ffmpeg的image2](http://underpop.online.fr/f/ffmpeg/help/image2-1.htm.gz)输入即可，语法相同。输出设置中，帧率不需要勾选，容器应选择视频容器，其他设置与普通视频转码相同。不知是不是符合你的需求？

**Comment by bjw321** [comment]
收到，谢谢大佬

**Comment by f-shake** [comment]
> 收到，谢谢大佬

客气了，我只是稍微懂一点，称不上大佬，甚至不是计算机专业的😂

刚刚提交了一个Release，可以直接使用

**Comment by bjw321** [comment]
嗯，我试用了一下，很好用，满足我的需求了

**Comment by f-shake** [comment]
> 嗯，我试用了一下，很好用，满足我的需求了

好的，那我Close了
