### ISSUE TITLE
剪切視頻介面無法使用

### ISSUE THREAD

**Issue by Shijinzakaue** [autodotua/RemoteFFmpegGUI#3]
用的是WPF_SelfContained版，進入剪切介面黑屏無法播放文件，請問哪裡出錯了?
![QQ截图20231210174113](https://github.com/autodotua/RemoteFFmpegGUI/assets/97389945/8495a016-cc38-47f9-9850-89253ccd0ebf)

**Comment by f-shake** [comment]
你好，我这边已确认最新版本确实存在这个问题，正在排查

**Comment by f-shake** [comment]
猜测问题源于所使用的Nuget包FFME.Windows不支持较新版本的ffmpeg所致：[ffmediaelement/issues/642](https://github.com/unosquare/ffmediaelement/issues/642)

该问题将在一周内进行处理。

**Comment by f-shake** [comment]
已通过使用其他版本Nuget包的方式解决了问题，已发布到Release。
