### ISSUE TITLE
能否在参数后面添加单位说明

### ISSUE THREAD

**Issue by breeze303** [autodotua/RemoteFFmpegGUI#6]
![image](https://github.com/user-attachments/assets/6e76ea76-9fd8-4258-83dc-f4d25467c115)
例如码率这一块添加单位说明，首次使用的时候不知道这个码率单位是多少只能瞎摸
以及CRF也是要调几次对比看区别才知道，希望大佬能在UI上增加相应的单位增加易用性，感谢大佬

**Comment by breeze303** [comment]
> ![image](https://private-user-images.githubusercontent.com/122870904/363818399-6e76ea76-9fd8-4258-83dc-f4d25467c115.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMjkzODQsIm5iZiI6MTcyNTMyOTA4NCwicGF0aCI6Ii8xMjI4NzA5MDQvMzYzODE4Mzk5LTZlNzZlYTc2LTlmZDgtNDI1OC04M2RjLWY0ZDI1NDY3YzExNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwM1QwMjA0NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDk0MTEzYTE2OWQ2OGRhMzFlY2YwZWNmMDBmNzk5MjlhZDk1OTVjZmM4NzhlODNiZDI2N2E1Nzk5NDhkMDZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yQTL4cidSfV4Gvn3RwMYBQpIRTDbPJyFI_62rHZfB04) 例如码率这一块添加单位说明，首次使用的时候不知道这个码率单位是多少只能瞎摸
以及CRF也是要调几次对比看区别才知道，希望大佬能在UI上增加相应的单位增加易用性，感谢大佬

**Comment by f-shake** [comment]
感谢你的建议，已经考虑在后续加入参数的单位显示以及参数功能说明，预计10月前可以完成。

**Comment by breeze303** [comment]
还有个建议是，可否增加一个批量转码，目前只能一个个选视频不能一整个文件夹选择

**Comment by f-shake** [comment]
> 还有个建议是，可否增加一个批量转码，目前只能一个个选视频不能一整个文件夹选择

目前选择文件这一块只能选择单个，后续会改为允许多选。目前可以在资源管理器中选中所有需要转的视频，拖进去，这样可以实现批量加入。

**Comment by breeze303** [comment]
> > 还有个建议是，可否增加一个批量转码，目前只能一个个选视频不能一整个文件夹选择
> 
> 目前选择文件这一块只能选择单个，后续会改为允许多选。目前可以在资源管理器中选中所有需要转的视频，拖进去，这样可以实现批量加入。

学到了，感谢

**Comment by im-dashan** [comment]
> > 还有个建议是，可否增加一个批量转码，目前只能一个个选视频不能一整个文件夹选择
> 
> 目前选择文件这一块只能选择单个，后续会改为允许多选。目前可以在资源管理器中选中所有需要转的视频，拖进去，这样可以实现批量加入。

希望尽快适配导入，文件夹，和，子文件夹（可选）这样是最好的批量解决方案，能只有选择多级文件内容批量转码，希望能根据cpu核心数量来默认同时处理的ffmpeg数量，多线程处理

**Comment by f-shake** [comment]
v20241030版本已添加参数后的单位显示，并支持在鼠标悬浮于参数标签或输入控件上方时弹出提示信息。
