### ISSUE TITLE
似乎不能导入文件夹批量处理，和多线程处理

### ISSUE THREAD

**Issue by im-dashan** [autodotua/RemoteFFmpegGUI#8]
似乎不能导入文件夹批量处理，希望能增加导入文件夹批量处理并且支持多线程，项目是个好项目，ui很美，加油

**Comment by f-shake** [comment]
已在2024年9月3日的commit中支持了导入文件夹或批量导入文件功能（点击底栏的“新增”按钮）。之前没有发布Release，现已在Release中发布最新版本。
多线程问题将在 #9 中一并回答。
